services:
  test:
    build:
      context: ./
      dockerfile: ./../Dockerfile-test
      args:
        SCRIPT_DIR: "social_media"
    environment:
      MOUNTEBANK_URL: "http://mountebank:2525"
      IMPOSTER_PORT: 4242
      SLACK_WEBHOOK_URL: "http://mountebank:4242"
